package com.example.clinifyauthorization.persistence.entity;// default package
// Generated 16 Jun 2023, 19:10:03 by Hibernate Tools 6.1.7.Final


import jakarta.persistence.*;

import java.sql.Time;
import java.sql.Timestamp;

import static jakarta.persistence.GenerationType.IDENTITY;

/**
 * Appointment generated by hbm2java
 */
@Entity
@Table(name="appointment"
    ,catalog="clinify"
)
public class Appointment  extends BaseEntity {


     private Integer id;
     private Doctor doctor;
     private Patient patient;
     private Timestamp date;
     private Time startTime;
     private Time endTime;
     private String creditCardLastFourDigits;
     private String status;
     private Integer rating;
     private String description;

    public Appointment() {
    }

	
    public Appointment(Doctor doctor, Timestamp date, Time startTime, Time endTime) {
        this.doctor = doctor;
        this.date = date;
        this.startTime = startTime;
        this.endTime = endTime;
    }
    public Appointment(Doctor doctor, Patient patient, Timestamp date, Time startTime, Time endTime, String creditCardLastFourDigits, String status, Integer rating, String description) {
       this.doctor = doctor;
       this.patient = patient;
       this.date = date;
//       this.startTime = startTime;
       this.endTime = endTime;
       this.creditCardLastFourDigits = creditCardLastFourDigits;
       this.status = status;
       this.rating = rating;
       this.description = description;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="doctor_id", nullable=false)
    public Doctor getDoctor() {
        return this.doctor;
    }
    
    public void setDoctor(Doctor doctor) {
        this.doctor = doctor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="patient_id")
    public Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Timestamp getDate() {
        return this.date;
    }
    
    public void setDate(Timestamp date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="start_time", nullable=false, length=8)
    public Time getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Time startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="end_time", nullable=false, length=8)
    public Time getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Time endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="credit_card_last_four_digits", length=4)
    public String getCreditCardLastFourDigits() {
        return this.creditCardLastFourDigits;
    }
    
    public void setCreditCardLastFourDigits(String creditCardLastFourDigits) {
        this.creditCardLastFourDigits = creditCardLastFourDigits;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="rating")
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    
    @Column(name="description", length=360)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


